---
# http://wiki.cacert.org/Exim4Configuration says to run exim-gencert but that
# produces 1024bit keys which no CA today will accept. The following
# configuration stanzas do the same thing but without prompting and using
# decent length keys.

# https://my.spamexperts.com/kb/33/generate-dkim-certificate.html
- name: Generate certificate for DKIM
  command: openssl genrsa -out {{ exim_transport_remote_smtp_dkim_private_key }} 2048
    creates={{ exim_transport_remote_smtp_dkim_private_key }}
  when: eximcsrmade.changed
  tags:
  - system
  - openssl
  - mail
  - exim
  - dkim

- name: Generate public key for DKIM
  command: openssl rsa -in {{ exim_transport_remote_smtp_dkim_private_key }} -out /etc/exim4/dkim.pub -pubout -outform PEM
    creates=/etc/exim4/dkim.pub
  tags:
  - system
  - openssl
  - mail
  - exim
  - dkim

- name: Restrict access to DKIM SSL related files
  file: mode=440 owner=root group=Debian-exim
    path=/etc/exim4/{{ item }}
  with_items:
    - dkim.key
    - dkim.pub
  tags:
  - system

