---

- name: Include OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: install-saslauthd.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure.yml

- include: configure-dkim-certificates.yml

- include: configure-fail2ban.yml
  when: exim_fail2ban_enable

